"""first migrates

Revision ID: e1f1ccb126eb
Revises: 2b8d4d9038ca
Create Date: 2023-02-21 14:10:25.609806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f1ccb126eb'
down_revision = '2b8d4d9038ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.drop_column('estado')

    op.drop_table('categorias_productos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
